packages:
  - packages/types
  - packages/docs
  - packages/builder
  - examples/env
  - examples/fetch
  - examples/file-system
  - examples/hello-world
  - tests

allowBuilds:
  esbuild: true
  sharp: false

minimumReleaseAge: 2880 # ignore dependency updates released less than 2 days ago

minimumReleaseAgeExclude:
  - kyushu-types@0.0.3
