use rquickjs::loader::{BuiltinLoader, BuiltinResolver};

pub fn add_to_resolver(resolver: BuiltinResolver) -> BuiltinResolver {
    resolver
        .with_module("__wasm_rquickjs_builtin/internal/http")
        .with_module("internal/http")
        .with_module("__wasm_rquickjs_builtin/internal/errors")
        .with_module("__wasm_rquickjs_builtin/internal/fs/utils")
        .with_module("__wasm_rquickjs_builtin/internal/fs/shared")
        .with_module("__wasm_rquickjs_builtin/internal/normalize_encoding")
        .with_module("__wasm_rquickjs_builtin/internal/url")
        .with_module("__wasm_rquickjs_builtin/internal/util")
        .with_module("__wasm_rquickjs_builtin/internal/validators")
        .with_module("__wasm_rquickjs_builtin/internal/streams/add-abort-signal")
        .with_module("__wasm_rquickjs_builtin/internal/binding/util_native")
        .with_module("__wasm_rquickjs_builtin/internal/binding/util")
        .with_module("__wasm_rquickjs_builtin/internal/test/binding")
        .with_module("__wasm_rquickjs_builtin/internal/streams/buffer_list")
        .with_module("__wasm_rquickjs_builtin/internal/streams/compose")
        .with_module("__wasm_rquickjs_builtin/internal/streams/destroy")
        .with_module("__wasm_rquickjs_builtin/internal/streams/duplex")
        .with_module("__wasm_rquickjs_builtin/internal/streams/end-of-stream")
        .with_module("__wasm_rquickjs_builtin/internal/streams/from")
        .with_module("__wasm_rquickjs_builtin/internal/streams/lazy_transform")
        .with_module("__wasm_rquickjs_builtin/internal/streams/legacy")
        .with_module("__wasm_rquickjs_builtin/internal/streams/passthrough")
        .with_module("__wasm_rquickjs_builtin/internal/streams/pipeline")
        .with_module("__wasm_rquickjs_builtin/internal/streams/readable")
        .with_module("__wasm_rquickjs_builtin/internal/streams/state")
        .with_module("__wasm_rquickjs_builtin/internal/streams/transform")
        .with_module("__wasm_rquickjs_builtin/internal/streams/utils")
        .with_module("__wasm_rquickjs_builtin/internal/streams/writable")
        .with_module("__wasm_rquickjs_builtin/internal/util/debuglog")
        .with_module("__wasm_rquickjs_builtin/internal/util/inspect")
        .with_module("__wasm_rquickjs_builtin/internal/util/types")
        .with_module("__wasm_rquickjs_builtin/internal/webstreams/util")
}

pub fn module_loader() -> BuiltinLoader {
    BuiltinLoader::default()
        .with_module(
            "__wasm_rquickjs_builtin/internal/http",
            include_str!("http.js"),
        )
        .with_module("internal/http", include_str!("http.js"))
        .with_module(
            "__wasm_rquickjs_builtin/internal/errors",
            include_str!("errors.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/fs/utils",
            include_str!("fs/utils.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/fs/shared",
            include_str!("fs/shared.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/normalize_encoding",
            include_str!("normalize_encoding.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/url",
            include_str!("url.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/util",
            include_str!("util.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/validators",
            include_str!("validators.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/binding/util",
            include_str!("binding/util.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/test/binding",
            include_str!("test/binding.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/add-abort-signal",
            include_str!("streams/add-abort-signal.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/buffer_list",
            include_str!("streams/buffer_list.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/compose",
            include_str!("streams/compose.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/destroy",
            include_str!("streams/destroy.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/duplex",
            include_str!("streams/duplex.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/end-of-stream",
            include_str!("streams/end-of-stream.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/from",
            include_str!("streams/from.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/lazy_transform",
            include_str!("streams/lazy_transform.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/legacy",
            include_str!("streams/legacy.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/passthrough",
            include_str!("streams/passthrough.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/pipeline",
            include_str!("streams/pipeline.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/readable",
            include_str!("streams/readable.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/state",
            include_str!("streams/state.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/transform",
            include_str!("streams/transform.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/utils",
            include_str!("streams/utils.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/streams/writable",
            include_str!("streams/writable.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/util/debuglog",
            include_str!("util/debuglog.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/util/inspect",
            include_str!("util/inspect.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/util/types",
            include_str!("util/types.js"),
        )
        .with_module(
            "__wasm_rquickjs_builtin/internal/webstreams/util",
            include_str!("webstreams_util.js"),
        )
}
