[package]
name = "kyushu-worker"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rquickjs = { workspace = true }
wasi = "0.14.7"
wstd = { workspace = true }
kyushu-runtime = { path = "../crates/runtime" }
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
