[package]
name = "kyushu-worker"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rquickjs = { workspace = true }
kyushu-runtime = { path = "../crates/runtime", default-features = false, features = ["p3", "normal-p3"] }
wit-bindgen = { version = "0.62.0", features = ["async", "async-spawn", "inter-task-wakeup"] }
