[package]
name = "kyushu-worker"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rquickjs = { workspace = true }
kyushu-runtime = { path = "../crates/runtime", default-features = false, features = ["p3", "normal-p3"] }
wit-bindgen-p3 = { workspace = true, features = ["realloc", "std", "bitflags"] }
